### PR TITLE
Fix for dropping nodes on same host in findMembers()

### PR DESCRIPTION
**Pull request by paulhoadley**
The issue here is described at length in #29. Here we:

* make the change in `findMembers()` suggested by @ctrimble;
* update JGroups from 4.0.5 → 4.2.15;
* make various refinements to `conf/aws_ping.xml`, mostly suggested by JGroups itself at startup.

### CODE REVIEW

**Comment by paulhoadley** [comment]
I am more than happy to back out the JGroups 4.0.5 → 4.2.15 update if anyone thinks it's too much to bundle with what is otherwise a 1-line fix here. @ctrimble: I can also test this further, including in a UAT-type environment with a real app, if you can kick out a SNAPSHOT.

**Comment by ctrimble** [comment]
I should have some time to look at this tonight.  I would like to keep the dependencies as constant as possible.  Maybe what we need is a version range.  In any case, we should not force people to upgrade JGroups if they do not need to.  This change didn't put us on any new parts of the API.

I see that you fixed issues with the Chat demo.  I think it is important to preserve those fixes.

**Comment by paulhoadley** [comment]
Let me know if you want me to close this and re-submit without the JGroups version update.

**Comment by ctrimble** [comment]
I need to give this a good look to see what needs to be done.  I might just cherry pick it, to get things moving.  I will also try to get you a SNAPSHOT to test against.

**Comment by paulhoadley** [comment]
> I might just cherry pick it, to get things moving.

By all means. Other than `a90a3e4`, everything here was just seizing the opportunity to update JGroups and tidy up. If you'd rather keep it to "fix one thing per PR", just cherry-pick your own 1-line fix up there and close this without merging.

**Comment by ctrimble** [comment]
My recent move to Big Sur is hating on the special user I have for pushing SNAPSHOTs/releases.  Sorry for the delay.

**Comment by paulhoadley** [comment]
No problem! Thanks for looking into this.

**Comment by paulhoadley** [comment]
Just for the record:

> We also remove `slf4j-simple` out of test scope.

This was a mistake. As explained in `8724948`, my thinking here was that you can't run `org.jgroups.demos.Chat` demo unless `slf4j-simple` is in scope. (Or, at least, you can't run the demo _and get logging output_.) However, putting `slf4j-simple` into `compile` scope (or even `runtime`) is _wrong:_ now you've got the `jgroups-aws` _library_ specifying an SLF4J implementation, which defeats the purpose of using SLF4J. (Not surprisingly, I noticed this when testing an application dependent on `jgroups-aws`: SLF4J complains that there are two implementations on the classpath, which is completely true.) So `slf4j-simple` should definitely be in `test` scope, and you can then salvage the demo by adding `-Dexec.classpathScope=test` to the command line:

```
mvn exec:java -Dexec.mainClass="org.jgroups.demos.Chat" -Dexec.args="-props conf/aws_ping.xml" -Djava.net.preferIPv4Stack=true -Dexec.classpathScope=test
```

In any case, the only useful commit from this PR has been cherry-picked, and at this point I'll just close it.

**Comment by ctrimble** [comment]
I still need to get you a release for this.

**Comment by paulhoadley** [comment]
Don't worry about it. I made other arrangements. Thanks for your help fixing the initial bug.

**Pull request closed without merging**
