### PR TITLE
Adapted to JGroups 4

### PR DESCRIPTION
**Pull request by jebl01**
Bumped jgroups dependency and made the necessary changes in code.
Tests are all green, -but untested in the wild...

### CODE REVIEW

**Comment by ctrimble** [comment]
@jebl01 is `timeout` not an option we are picking up from Discovery anymore?  If so, there are more comments about this option in the `Javadoc` for `AWS_PING`.

The test suite does not do a practical test of the code in AWS.  I am happy to pull this in, but I will need you to run it in AWS to verify that it works.  Last time we had an update like this, I pushed a SNAPSHOT for testing, the user submitting verified it, and then we merged.  Will that work for you?

**Comment by ctrimble** [comment]
One more note, I will be on vacation next week.  So, if we can get this verified in the next couple of days, I can have it merged and on central by Friday.  Otherwise, we will need to wait 7/17 to get this released.

**Comment by jebl01** [comment]
`timeout` was removed in: https://github.com/belaban/JGroups/commit/041c01b3830212203f8d575fa49fd6312f420b58
*deprecated message*: `GMS.join_timeout should be used instead`

If there is time, I will try to fire it up in AWS today, if not, it will have to wait until August (throwing in the towel tomorrow -> Sweden == 5 weeks summer vacay :-)

**Comment by ctrimble** [comment]
@jebl01 I pushed this to Sonatype's OSS repository with version `1.5.0-SNAPSHOT`.

**Comment by jebl01** [comment]
ok, I'll try it!
One thing to note is that *jgroups* 4.0.1 logs formatted traces as info. This is reported and resolved:
https://issues.jboss.org/browse/JGRP-2201
Since this version of *jgroups-aws* still depends on *jgroups* 4.0.1 logs might be more verbose than expected...

**Comment by jebl01** [comment]
verified on AWS and it flies...

Expect an other PR soon on this chunk:
```java
if (physical_addr != null && addr.equals(physical_addr))
    continue;
```
It doesn't take ports into account and hence `a.b.c.d:x` tries to connect to itself on all other ports in the range (i.e. `a.b.c.d:[^x]`)

My take on it is something like:
```java
addr.getIpAddress().equals(physical_addr.getIpAddress()
```

**Comment by ctrimble** [comment]
Should I cut a release of this, or should we wait for the other PR to come in?

**Comment by jebl01** [comment]
Ship it!

**Comment by ctrimble** [comment]
Released.  This should be available on central in a couple of hours.

**Pull request merged**
