### PR TITLE
Updating jgroups-aws for JGroups 3.6.6 (Broken since 3.5.0)

### PR DESCRIPTION
**Pull request by ctrimble**
related to #4

AWS_PING protocol broke when `Discovery.fetchClusterMembers` was removed in this JGroups commit: https://github.com/belaban/JGroups/commit/e97fd870739b18acf96e05a82342d457bf6a8c97
This commit fixes the protocol by implementing `Discovery.findMembers` instead.

Two classloader tests were broken. Fixing them should be trivial but as I was unsure of their purpose I chose to simply disable the tests instead.

Before merging this, we should resolve why the class loading behavior of JGroups changed.  This is important when clustering WARs.

### CODE REVIEW

**Comment by ctrimble** [comment]
@Shabin you may be interested in this.

**Comment by kenwdelong** [comment]
This would be of great help to me.  I am facing a bug in 3.1.0 and I need to upgrade.

**Comment by ctrimble** [comment]
@kenwdelong the only thing preventing me from pulling this in is testing.  I just found it in one of the forks.  If you can verify that it works I will be happy to merge it in and create a release.

**Comment by ctrimble** [comment]
@kenwdelong Would a SNAPSHOT up on Sonatype's repository help your efforts?

**Comment by kenwdelong** [comment]
Yes!!  A snapshot would help.  I need to test this in a distributed config (of course) so I'll need to set up a staging env etc, so it will take me a day or so.

**Comment by ctrimble** [comment]
@kenwdelong I have changed the current master to `1.3.2-SNAPSHOT`, since it looks like `1.3.x` will be the last minor to support older versions of JGroups.

This PR has been deployed to version `1.4.0-SNAPSHOT` in Sonatype's repository.  If your testing goes well, I will merge this onto master and cut a release.

**Comment by kenwdelong** [comment]
Looks like the 1.4.0-SNAPSHOT is actually the master branch; in any event, the POM still has JGroups dependency at 3.1.0.Final.

I will attempt to build the branch locally to see if I can get it working.

**Comment by ctrimble** [comment]
I didn't update the source or javadoc, but the correct pom and jar are linked from the metadata.  Not sure what the issue is.

- [pom.xml](https://oss.sonatype.org/content/repositories/snapshots/com/meltmedia/jgroups/jgroups-aws/1.4.0-SNAPSHOT/jgroups-aws-1.4.0-20160323.210952-5.pom)
- [maven-metadata.xml](https://oss.sonatype.org/content/repositories/snapshots/com/meltmedia/jgroups/jgroups-aws/1.4.0-SNAPSHOT/maven-metadata.xml)

**Comment by ctrimble** [comment]
@kenwdelong I gave this deploy one more shot.  There should be current sources, javadocs, pom and jar for this PR deployed to 1.4.0-SNAPSHOT now.

**Comment by kenwdelong** [comment]
Ok, I've done what testing I can think of and everything seems to be working correctly.  I even upgraded JGroups to 3.6.8.Final and that is working too.  I think you are good to release 1.4.0.  Maybe you could update to POM to 3.6.8, just to get the cutting edge?

Thanks again so much for your help!

**Comment by ctrimble** [comment]
Thanks for testing this.  I am sure others using the project will appreciate it.  If you ever need anything else updated for the project, do not hesitate to ask.

I will merge this PR, update to 3.6.8 and release.  We probably also need a version matrix in the README now, as well.

**Pull request merged**
